version: '3.5'

services:
  db:
    build:
      context: ./services/form_handler/main/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  form-handler:
    container_name: form-handler
    build:
      context: ./services/form_handler
      dockerfile: Dockerfile
    volumes:
      - './services/form_handler:/usr/app'
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=main.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/db_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/db_test
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    depends_on:
      - form-handler
      - web-form

  web-form:
    container_name: web-form
    build:
      context: ./web_form
      dockerfile: Dockerfile
    volumes:
      - './web_form:/usr/app'
      - '/usr/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - REACT_APP_BASE_API_URL=http://localhost/api
    depends_on:
      - form-handler